name: neuron

services:
  postgres:
    container_name: postgres
    image: pgvector/pgvector:pg17
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: pg_isready -U admin -d main
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  broker:
    container_name: broker
    build:
      context: .
      dockerfile: bins/broker/Dockerfile
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/main
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  worker:
    container_name: worker
    build:
      context: .
      dockerfile: bins/worker/Dockerfile
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/main
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
      ROUTING_CANDIDATE_LIMIT: 5
      ROUTING_MIN_CONFIDENCE: 0.20
      ROUTING_AMBIGUITY_MARGIN: 0.05
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
