services:
  api:
    build:
      target: builder
    working_dir: /app
    volumes:
      - .:/app
      - api-target:/app/target
      - cargo-registry:/usr/local/cargo/registry
    command: cargo run --release --package api

  executor:
    build:
      target: builder
    working_dir: /app
    environment:
      NEURON_CACHE: /app/.cache
    volumes:
      - .:/app
      - executor-target:/app/target
      - cargo-registry:/usr/local/cargo/registry
      - ./.cache:/app/.cache
    command: cargo run --release --package executor

volumes:
  api-target:
  executor-target:
  cargo-registry:
