services:
  broker:
    build:
      target: builder
    working_dir: /app
    environment:
      CONSOLE_ENABLED: true
      CONSOLE_TENANT_ID: 775a179d-9819-42c0-ab47-637bf96fbf7b
    volumes:
      - .:/app
      - broker-target:/app/target
      - cargo-registry:/usr/local/cargo/registry
    command: cargo run --release --package broker

  worker:
    build:
      target: builder
    working_dir: /app
    environment:
      NEURON_CACHE: /app/.cache
    volumes:
      - .:/app
      - worker-target:/app/target
      - cargo-registry:/usr/local/cargo/registry
      - ./.cache:/app/.cache
    command: cargo run --release --package worker

volumes:
  broker-target:
  worker-target:
  cargo-registry:
